---
# Setup vagrant boxes

- block:
    - name: get vagrant boxes list
      shell: vagrant --machine-readable box list
      changed_when: false
      register: vagrant_provisioner_get_boxes_result

    - import_tasks: "{{ vagrant_provisioner_boxes_provisioning_include }}"
      vars:
        method: "{{ vagrant_provisioner_boxes_provisioning_method }}"
        vagrant_provisioner_boxes_provisioning_include: >-
          {{ (method == "asynchronous")
             | ternary("boxes_provisioning_asynchronous.yml",
                       "boxes_provisioning_sequential.yml") }}

    - block:
        - name: build vagrant boxes
          include_tasks: build_boxes.yml
          when: vagrant_provisioner_boxes_vms | length > 0

        - name: search temporary vms created to build boxes
          find:
            paths: "{{ vagrant_provisioner_vms_directory | expanduser }}"
            recurse: yes
            patterns: >-
              {{ lookup('template', 'boxes_to_build.j2') | from_yaml
                 | map(attribute="name")
                 | map("basename")
                 | map("regex_replace", "(.*)", "^\1$")
                 | list }}
            use_regex: yes
            file_type: directory
          vars:
              vagrant_provisioner_boxes_force_build: true
          register: vagrant_sandbox_search_boxes_vms_result

        - name: drop temporary vms created to build boxes
          include_tasks: vms.yml
          when: vagrant_provisioner_boxes_vms_created | length > 0
          vars:
           vagrant_provisioner_vm_state: "absent"
           vagrant_provisioner_vms: "{{ vagrant_provisioner_boxes_vms }}"
           vagrant_provisioner_boxes_force_build: true
      vars:
        vagrant_provisioner_boxes_found: >-
          {{ vagrant_provisioner_get_boxes_result.stdout.splitlines()
             | select("search", ",box-name,")
             | map("regex_replace", ".*box-name,(.*)", "\1")
             | list }}
        vagrant_provisioner_boxes_setup_name_attribute: >-
          {{ (vagrant_provisioner_boxes_provisioning_method == "asynchronous")
             | ternary("async_item.box.1.name", "box.1.name")
          }}
        vagrant_provisioner_boxes_changed: >-
          {{ vagrant_provisioner_boxes_setup_result.results
             | select("changed")
             | map(attribute=vagrant_provisioner_boxes_setup_name_attribute)
             | list }}
        vagrant_provisioner_boxes_undefined: >-
          {{ vagrant_provisioner_boxes
             | selectattr("playbook", "defined")
             | selectattr("state", "undefined")
             | list }}
        vagrant_provisioner_boxes_to_build: >-
          {{ vagrant_provisioner_boxes
             | difference(vagrant_provisioner_boxes_undefined)
             | selectattr("playbook", "defined")
             | selectattr("state", "equalto", "present")
             | list
             + (vagrant_provisioner_box_state == "present")
               | ternary(vagrant_provisioner_boxes_undefined, []) }}
        vagrant_provisioner_boxes_vms: >-
          {{ lookup('template', 'boxes_to_build.j2') | from_yaml }}

        vagrant_provisioner_boxes_vms_created: >-
          {{ vagrant_sandbox_search_boxes_vms_result.files
             | selectattr("path", "defined")
             | map(attribute="path")
             | map("basename")
             | list }}
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::boxes
