---
# Role tasks

- name: setup vagrant plugins
  include_tasks: plugins.yml
  when: vagrant_provisioner_plugins | length > 0
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::plugins

- name: setup vagrant boxes
  include_tasks: boxes.yml
  when: vagrant_provisioner_boxes | length > 0
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::boxes

- block:
    - name: setup vagrant virtual machines
      include_tasks: vm.yml
      with_items: "{{ vagrant_provisioner_vms }}"
      loop_control:
        label: "{{ vm.hostname }}"
        loop_var: vm

    - name: save inventory file with the provisioned vms
      include_tasks: inventory.yml
      when:
        - vagrant_provisioner_up_result is defined
        - vagrant_provisioner_up_result | changed
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::vms
