---
# Setup vagrant plugins

- name: install vagrant plugins
  shell: "vagrant plugin install {{ plugin.name }}"
  register: vagrant_provisioner_plugin_install_result
  failed_when: >-
    not vagrant_provisioner_plugin_install_result.stdout
        | search("Installed the plugin .*" + plugin.name)
  when:
    - plugin.state == "present"
    - >-
        lookup("pipe",
               "vagrant plugin list | grep " + plugin.name + " || true")
        | length == 0
  with_items: "{{ vagrant_provisioner_plugins }}"
  loop_control:
    label: "{{ plugin.name }}"
    loop_var: plugin

- name: uninstall vagrant plugins
  shell: "vagrant plugin uninstall {{ plugin.name }}"
  register: vagrant_provisioner_plugin_install_result
  failed_when: >-
    not vagrant_provisioner_plugin_install_result.stdout
        | search("Successfully uninstalled .*" + plugin.name)
  when:
    - plugin.state == "absent"
    - >-
        lookup("pipe",
               "vagrant plugin list | grep " + plugin.name + " || true")
        | length > 0
  with_items: "{{ vagrant_provisioner_plugins }}"
  loop_control:
    label: "{{ plugin.name }}"
    loop_var: plugin
