---
# Setup vagrant plugins

- block:
    - name: Get vagrant plugin list
      command: vagrant plugin list
      changed_when: no
      register: vagrant_provisioner_get_plugins_result

    - name: Setup vagrant plugins
      command: >-
        vagrant plugin
        {{ (plugin.state == "present") | ternary("install", "uninstall") }}
        {{ plugin.name }}
      register: vagrant_provisioner_plugin_setup_result
      failed_when:
        plugin.state == "present"
        and not vagrant_provisioner_plugin_setup_result.stdout
                is search("Installed the plugin .*" + plugin.name)
        or plugin.state == "absent"
           and not vagrant_provisioner_plugin_setup_result.stdout
                   is search("Successfully uninstalled .*" + plugin.name)
      when: >-
        (plugin.state == "present"
         and not vagrant_provisioner_get_plugins_result.stdout
                 is search(plugin.name))
        or (plugin.state == "absent"
            and vagrant_provisioner_get_plugins_result.stdout
                is search(plugin.name))
      loop: "{{ vagrant_provisioner_plugins }}"
      loop_control:
        label: "{{ plugin.name }}"
        loop_var: plugin
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::plugins
