---
# Setup vagrant vms

- block:
    - name: provisione vagrant virtual machine
      include_tasks: vm_provision.yml
      when: vm.state | default(vagrant_provisioner_vm_state )== "started"

    - name: destroy vagrant virtual machine
      include_tasks: vm_destroy.yml
      when: vm.state | default(vagrant_provisioner_vm_state )== "absent"
  vars:
    vm_path: >-
      {{ vm.directory
         | default(vagrant_provisioner_vms_directory
                   | expanduser
                   + "/"
                   + vm.name) }}
