---
# Setup vagrant vms

- block:
    - name: Get current vms facts
      import_tasks: vms_facts.yml

    - name: Remove ssh known_hosts entries for hosts that will be deleted
      known_hosts:
        name: "[{{ item.1.ansible_host }}]:{{ item.1.ansible_port }}"
        key: "{{ item.1.ssh_public_keys | default('') }}"
        hash_host: no
        state: absent
      loop: >-
        {{ vagrant_provisioner_known_hosts_dest
           | product(vms_known_hosts
                     | selectattr("name",
                                  "in",
                                  vagrant_provisioner_vms_state_absent
                                  | map(attribute="name")
                                  | list)
                     | list) }}
      loop_control:
        index_var: index
        label: >-
          {{ item.1.name }}
          {{ item.1.ansible_host }}:{{ item.1.ansible_port }}
      delegate_to: "{{ item.0 }}"

    - name: Create vagrant virtual machines directories
      file:
        path: "{{ vm_path }}"
        state: directory
        force: yes
        mode: 0700
      loop: "{{ vagrant_provisioner_vms_state_started }}"
      loop_control:
        label: "{{ vm.hostname }}"
        loop_var: vm

    - name: Create vagrant config file for virtual machines
      template:
        src: Vagrantfile.j2
        dest: "{{ vm_path }}/Vagrantfile"
        mode: 0600
      register: vagrant_provisioner_create_vagrantfile_result
      loop: "{{ vagrant_provisioner_vms_state_started }}"
      loop_control:
        label: "{{ vm.hostname }}"
        loop_var: vm

    - import_tasks: "{{ vagrant_provisioner_vms_provisioning_include }}"
      vars:
        method: "{{ vagrant_provisioner_vms_provisioning_method }}"
        vagrant_provisioner_vms_provisioning_include: >-
          {{ (method == "asynchronous")
             | ternary("vms_asynchronous.yml",
                       "vms_sequential.yml") }}

    - name: Refresh provisioned virtual machine facts
      import_tasks: vms_facts.yml

    - name: Create .ssh directory
      file:
        path: >-
          {{ (ansible_facts.env
              | default(ansible_facts.ansible_env))["HOME"] }}/.ssh"
        state: directory
        mode: 0700
      loop: "{{ vagrant_provisioner_known_hosts_dest }}"
      delegate_to: "{{ item }}"

    - name: Setup ssh known_hosts entries
      known_hosts:
        name: "[{{ item.1.ansible_host }}]:{{ item.1.ansible_port }}"
        key: "{{ item.1.ssh_public_keys | default('') }}"
        hash_host: no
        state: "{{ key_state }}"
      loop: >-
        {{ vagrant_provisioner_known_hosts_dest | product(vms_known_hosts) }}
      loop_control:
        index_var: index
        label: >-
          {{ item.1.name }}
          {{ item.1.ansible_host }}:{{ item.1.ansible_port }}
      vars:
        vm_state: "{{ item.1.state | default(vagrant_provisioner_vm_state) }}"
        key_state: >-
          {{ (vm_state== "started")
             | ternary("present",
                       (vm_state == "stopped" or vm_state == "absent")
                       | ternary("absent", item.1.state)) }}
      delegate_to: "{{ item.0 }}"

    - name: Associate inventory info to managed vagrant virtual machines
      add_host:
        name: "{{ vm.name }}"
        groups: "{{ vm.groups }}"
        ansible_connection: "{{ vm.ansible_connection }}"
        ansible_host: "{{ vm.ansible_host }}"
        ansible_port: "{{ vm.ansible_port }}"
        ansible_user: "{{ vm.ansible_user }}"
        ansible_ssh_pass: "{{ vm.ansible_ssh_pass }}"
        ansible_ssh_private_key_file: "{{ vm.ansible_ssh_private_key_file }}"
        ansible_ssh_common_args: "{{ vm.ansible_ssh_common_args }}"
        ansible_scp_extra_args: "{{ vm.ansible_scp_extra_args }}"
        ansible_ssh_extra_args: "{{ vm.ansible_ssh_extra_args }}"
        ansible_ssh_pipelining: "{{ vm.ansible_ssh_pipelining }}"
        ansible_ssh_executable: "{{ vm.ansible_ssh_executable }}"
        ansible_become: "{{ vm.ansible_become }}"
        ansible_become_method: "{{ vm.ansible_become_method }}"
        ansible_become_user: "{{ vm.ansible_become_user }}"
        ansible_become_pass: "{{ vm.ansible_become_pass }}"
        ansible_become_exe: "{{ vm.ansible_become_exe }}"
        ansible_become_flags: "{{ vm.ansible_become_flags }}"
        ansible_python_interpreter: "{{ vm.ansible_python_interpreter }}"
        ansible_shell_executable: "{{ vm.ansible_shell_executable }}"
        ssh_public_keys: "{{ vm.ssh_public_keys | default('') }}"
      changed_when: no
      when: vagrant_provisioner_in_memory_inventory | bool
      loop: >-
        {{ vagrant_provisioner_vms_facts
           | selectattr("ansible_user", "defined")
           | list }}
      loop_control:
        label: "{{ vm.name }} {{ vm.ansible_host }}:{{ vm.ansible_port }}"
        loop_var: vm
      delegate_to: localhost

    - name: Associate inventory info to unmanaged vagrant virtual machines
      add_host:
        name: "{{ vm.name }}"
        groups: "{{ vm.groups }}"
        ansible_connection: "{{ vm.ansible_connection }}"
        ansible_host: "{{ vm.ansible_host }}"
        ansible_port: "{{ vm.ansible_port }}"
        ansible_ssh_private_key_file: "{{ vm.ansible_ssh_private_key_file }}"
        ssh_public_keys: "{{ vm.ssh_public_keys | default('') }}"
      changed_when: no
      when: vagrant_provisioner_in_memory_inventory | bool
      loop: >-
        {{ vagrant_provisioner_vms_facts
           | selectattr("ansible_connection", "defined")
           | selectattr("ansible_host", "defined")
           | selectattr("ansible_port", "defined")
           | selectattr("ansible_ssh_private_key_file", "defined")
           | selectattr("ansible_user", "undefined")
           | list }}
      loop_control:
        label: "{{ vm.name }} {{ vm.ansible_host }}:{{ vm.ansible_port }}"
        loop_var: vm
      delegate_to: localhost

    - name: Remove vagrant absent virtual machines directories
      file:
        path: "{{ vm_path }}"
        state: absent
        force: yes
      when: >-
        not vm.name in
            vagrant_provisioner_vms_setup_result.results
            | select("failed")
            | selectattr("vm.name")
            | list
      loop: "{{ vagrant_provisioner_vms_state_absent }}"
      loop_control:
        label: "{{ vm.name }}"
        loop_var: vm
  vars:
    vms_known_hosts: >-
      {{ vagrant_provisioner_vms_facts
         | selectattr("ansible_host", "defined")
         | selectattr("ansible_port", "defined")
         | selectattr("ssh_public_keys", "defined")
         | list }}
    vm_path: >-
      {{ vm.directory
         | default(vagrant_provisioner_vms_path | expanduser
                   + "/"
                   + vm.name) }}
  tags:
    - role::vagrant_provisioner
    - role::vagrant_provisioner::vms
