---
# Get current containers facts

- block:
    - name: get vagrant virtual machines global status
      shell: >-
        vagrant global-status --prune
        | grep -E '....... +.* +virtualbox|libvirt|vmware + .* + .*'
        | grep '/'
        | awk '{ print $1,$2,$3,$4,$5 }'
      register: vagrant_provisioner_get_global_status_result
      changed_when: false
      check_mode: no

    - name: get vagrant virtual machines ssh config
      shell: vagrant ssh-config
      args:
        chdir: "{{ status.split(' ').4 }}"
      when:
        - vagrant_provisioner_get_global_status_result.stdout | length > 0
        - status.split(' ').3 == "running"
      register: vagrant_provisioner_ssh_config_result
      changed_when: false
      loop: "{{ global_status }}"
      loop_control:
        label: "{{ status.split(' ').1 }}"
        loop_var: status
      check_mode: no
      vars:
        global_status: >-
          {{ vagrant_provisioner_get_global_status_result.stdout_lines }}

    - name: read vagrant virtual machines directories
      stat:
        path: "{{ vm.vagrant_path }}"
      register: vagrant_provisioner_check_vms_paths_result
      loop: "{{ vms }}"
      loop_control:
        label: "{{ vm.name }}"
        loop_var: vm
      check_mode: no
      vars:
        vms: "{{ lookup('template', 'facts.j2') | from_yaml }}"

    - name: gather vagrant virtual machines ssh public keys
      shell: >-
        ssh-keyscan \
        -T \
        {{ vm.public_key_scan_timeout
           | default(vagrant_provisioner_vm_public_key_scan_timeout) }} \
        -p {{ vm.ansible_port }} \
        {{ vm.ansible_host }}
      when: vagrant_provisioner_known_hosts_dest | length > 0
      register: vagrant_provisioner_get_public_keys_result
      changed_when: false
      loop: "{{ vms | selectattr('state', 'equalto', 'started') | list }}"
      loop_control:
        label: "{{ vm.name }} {{ vm.ansible_host }}:{{ vm.ansible_port }}"
        loop_var: vm
      check_mode: no
      vars:
        vms: "{{ lookup('template', 'facts.j2') | from_yaml }}"

    - name: setup fact with facts ansible-playbook in-memory info
      set_fact:
        vagrant_provisioner_vms_facts: >-
          {{ lookup('template', 'facts.j2') | from_yaml }}
  tags:
    - role::docker_provisioner
    - role::docker_provisioner::containers
