---

- name: Converge
  hosts: localhost
  gather_facts: no
  roles:
    - role: amtega.vagrant_provisioner
      vars:
        vagrant_provisioner_vm_state: started
  tasks:
    - name: Check provisioned virtual machines connection
      command: >-
        ansible -m setup
        -i {{ vagrant_provisioner_inventory }}
        {{ vm.name }}
      changed_when: no
      loop: >-
        {{ vagrant_provisioner_vms_facts
           | selectattr("groups.0", "equalto", "vagrant_provisioner_vms")
           | list }}
      loop_control:
        loop_var: vm
        label: >-
          {{ vm.name }}
          {{ vm.ansible_host }}:{{ vm.ansible_port }}
